// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzwrypihvpxpgnftnwli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6d3J5cGlodnB4cGduZnRud2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4Njk5NjYsImV4cCI6MjA2NzQ0NTk2Nn0.Qv_aVuye613EgiyEBBk7TFfGHC67kK6bQ8mVLcwkah0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});